version: "2.1"

services:

  selenium:
    image: selenium/standalone-chrome-debug:3.6.0
    ports:
      - "4444:4444"
      - "5900:5900"

  policygui:
    build: root 
    ports:
      - "8585:8585"
    command: -m
